"""
Automatic PDF Incident Report
"""

import os
from datetime import datetime
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet


class ReportGenerator:

    def __init__(self):

        os.makedirs("reports", exist_ok=True)

    def generate(self, event):

        filename = datetime.now().strftime(
            "reports/FallReport_%Y%m%d_%H%M%S.pdf"
        )

        doc = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        story = []

        story.append(
            Paragraph(
                "<b>AI FALL DETECTION INCIDENT REPORT</b>",
                styles["Title"]
            )
        )

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                f"<b>Timestamp:</b> {event['timestamp']}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"<b>Track ID:</b> {event['track_id']}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"<b>State:</b> {event['state']}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"<b>Confidence:</b> {event['confidence']:.2f} %",
                styles["Normal"]
            )
        )

        story.append(Spacer(1, 15))

        f = event["features"]

        story.append(
            Paragraph(
                f"Body Angle : {f['body_angle']}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"Velocity : {f['velocity']}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"Ground Time : {f['ground_time']}",
                styles["Normal"]
            )
        )

        story.append(
            Paragraph(
                f"Aspect Ratio : {f['aspect_ratio']}",
                styles["Normal"]
            )
        )

        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                "This report was automatically generated by the AI Fall Detection System.",
                styles["Italic"]
            )
        )

        doc.build(story)

        print(f"[REPORT] Generated: {filename}")

        return filename